name: vibra_project
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_web_auth_2: ^4.1.0
  http: ^1.2.1
  shared_preferences: ^2.5.4
  google_sign_in: ^6.2.1
  firebase_core: ^3.3.0
  intl: 0.20.2
  firebase_auth: ^5.1.4
  google_fonts: ^6.0.0
  url_launcher: ^6.1.11
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  share_plus: ^12.0.1
  provider: ^6.1.2
  path_provider: ^2.1.2
  app_settings: ^7.0.0
  permission_handler: ^12.0.1
  cloud_firestore: ^5.0.1
  logger: ^2.3.0 
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_acrcloud: ^0.2.2
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.6.3
  build_runner: ^2.11.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/googleLogo.png
    - assets/spotifyLogo.png
    - assets/vibraLogo.png
    - .env
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800